🌟Exercise 2: Dataset Loading and Initial Analysis


Objective: Practice dataset loading from Kaggle and initial analysis.
Task:
for the following dataset : How Much Sleep Do Americans Really Get?, Global Trends in Mental Health Disorder and Credit Card Approvals.

Load the dataset into Jupyter or Google Colab.
Display the first few rows.
Provide a brief dataset description.

🌟Exercise 3: Identifying Data Types

Objective: Learn to identify different data types.
Task:
For the datasets from the previous exercise, categorize each column of it as either quantitative or qualitative and explain your reasoning.

In [1]:
import pandas as pd

In [7]:
sleep_data = pd.read_csv('./How Much Sleep Do Americans/Time Americans Spend Sleeping.csv')
sleep_data.head()

,index,Year,Period,Avg hrs per day sleeping,Standard Error,Type of Days,Age Group,Activity,Sex
0,0,2003,Annual,8.57,0.018,All days,15 years and over,Sleeping,Both
1,1,2004,Annual,8.55,0.026,All days,15 years and over,Sleeping,Both
2,2,2005,Annual,8.62,0.023,All days,15 years and over,Sleeping,Both
3,3,2006,Annual,8.63,0.024,All days,15 years and over,Sleeping,Both
4,4,2007,Annual,8.57,0.024,All days,15 years and over,Sleeping,Both

Year - Qualitative because we can't get any useful information by making arithmetic operations on this column.

Period - Qualitative, because it's a label.

AVG hours per day sleeping - Qualitative because it's a continuous value.

Standard Error - Qualitative because it's a continuous value.

Types of Days - Qualitative, because it's a label.

Age Group - Qualitative, because it's a label.

Activity - Qualitative, because it's a label.

Sex - Qualitative, because it's a label.

In [3]:
global_trends_mental_health = pd.read_csv('./Global Trends in Mental Health Disorder/Mental health Depression disorder Data.csv', header=None)
global_trends_mental_health.head()

C:\Users\idob5\AppData\Local\Temp\ipykernel_4608\547554520.py:1: DtypeWarning: Columns (0: 0, 1: 5, 2: 6, 3: 7, 4: 8, 5: 9, 6: 10) have mixed types. Specify dtype option on import or set low_memory=False.
  global_trends_mental_health = pd.read_csv('./Global Trends in Mental Health Disorder/Mental health Depression disorder Data.csv', header=None)

,0,1,2,3,4,5,6,7,8,9,10
0,index,Entity,Code,Year,Schizophrenia (%),Bipolar disorder (%),Eating disorders (%),Anxiety disorders (%),Drug use disorders (%),Depression (%),Alcohol use disorders (%)
1,0,Afghanistan,AFG,1990,0.16056,0.697779,0.101855,4.82883,1.677082,4.071831,0.672404
2,1,Afghanistan,AFG,1991,0.160312,0.697961,0.099313,4.82974,1.684746,4.079531,0.671768
3,2,Afghanistan,AFG,1992,0.160135,0.698107,0.096692,4.831108,1.694334,4.088358,0.670644
4,3,Afghanistan,AFG,1993,0.160037,0.698257,0.094336,4.830864,1.70532,4.09619,0.669738

Entity - Qualitative, because it's a label.

Code - Qualitative, because it's a label.

Year - Qualitative because we can't get any useful information by making arithmetic operations on this column.

Schizophrenia - Qualitative because it's a continuous value.

Bipolar disorders - Qualitative because it's a continuous value.

Eating disorders - Qualitative because it's a continuous value.

Anxiety disorders - Qualitative because it's a continuous value.

Drug use disorders - Qualitative because it's a continuous value.

Depression - Qualitative because it's a continuous value.

Alcohol use disorders - Qualitative because it's a continuous value.

In [4]:
credit_card_approvals = pd.read_csv('./Credit Card Approvals (Clean Data)/clean_dataset.csv', header=None)
credit_card_approvals.head()

,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15
0,Gender,Age,Debt,Married,BankCustomer,Industry,Ethnicity,YearsEmployed,PriorDefault,Employed,CreditScore,DriversLicense,Citizen,ZipCode,Income,Approved
1,1,30.83,0.0,1,1,Industrials,White,1.25,1,1,1,0,ByBirth,00202,0,1
2,0,58.67,4.46,1,1,Materials,Black,3.04,1,1,6,0,ByBirth,00043,560,1
3,0,24.5,0.5,1,1,Materials,Black,1.5,1,0,0,0,ByBirth,00280,824,1
4,1,27.83,1.54,1,1,Industrials,White,3.75,1,1,5,1,ByBirth,00100,3,1

Gender - Qualitative, because it's a label.

Age - Qualitative because it's a continuous value.

Debt - Qualitative because it's a continuous value.

Married - Qualitative, because it's a label.

BankCustomer - Qualitative, because it's a label.

Industry - Qualitative, because it's a label.

Ethnicity - Qualitative, because it's a label.

YearsEmployed - Qualitative because it's a continuous value.

PriorDefault - Qualitative, because it's a label.

Employed - Qualitative, because it's a label.

CreditScore - Qualitative, because it's a label. Score of 8 for example, isn't necessarily twice better than Score of 4.

DriversLicense - Qualitative, because it's a label.

Citizen - Qualitative, because it's a label.

ZipCode - Qualitative, because it's a label. Making arithmetic operations on zipcodes doesn't provide any useful information.

Income - Qualitative because it's a continuous value.

Approved - Qualitative, because it's a label.

🌟Exercise 4: Exploring Data Types

Objective: Learn about different types of data in data analysis.
Task:
Load the Iris dataset using Kaggle into a Jupyter Notebook or Google Colaboratory Notebook.
Identify and list which columns in your dataset are qualitative and which are quantitative.
Write a brief description of why each column is classified as qualitative or quantitative.
Tools: Jupyter Notebook, Python with Pandas library.

In [5]:
import kagglehub
from kagglehub import KaggleDatasetAdapter

c:\Users\idob5\miniconda3\envs\data-analysis\Lib\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

In [6]:
file_path = "iris.csv"
df = kagglehub.dataset_load(KaggleDatasetAdapter.PANDAS, "himanshunakrani/iris-dataset", file_path)
df.head()

Downloading to C:\Users\idob5\.cache\kagglehub\datasets\himanshunakrani\iris-dataset\versions\1\iris.csv...

100%|██████████| 3.77k/3.77k [00:00<00:00, 3.59MB/s]

   sepal_length  sepal_width  petal_length  petal_width species
0           5.1          3.5           1.4          0.2  setosa
1           4.9          3.0           1.4          0.2  setosa
2           4.7          3.2           1.3          0.2  setosa
3           4.6          3.1           1.5          0.2  setosa
4           5.0          3.6           1.4          0.2  setosa

sepal_length - Qualitative because it's a continuous value. Arithmetic operations are useful on this column.

sepal_width - Qualitative because it's a continuous value. Arithmetic operations are useful on this column.

petal_length - Qualitative because it's a continuous value. Arithmetic operations are useful on this column.

petal_width - Qualitative because it's a continuous value. Arithmetic operations are useful on this column.

species - Qualitative, because it's a label.

🌟Exercise 5: Basic Observation Skills in Data Analysis


Objective: Develop observation skills for data analysis.
Task:
Load the How Much Sleep Do Americans Really Get? dataset into Jupyter or Google Colab.
Identify columns that could be interesting for a specific type of analysis (e.g., trend analysis, group comparison) and explain your choice.
Tools: Jupyter Notebook, Python with Pandas library.

In [14]:
sleep_data.head(16)

,index,Year,Period,Avg hrs per day sleeping,Standard Error,Type of Days,Age Group,Activity,Sex
0,0,2003,Annual,8.57,0.018,All days,15 years and over,Sleeping,Both
1,1,2004,Annual,8.55,0.026,All days,15 years and over,Sleeping,Both
2,2,2005,Annual,8.62,0.023,All days,15 years and over,Sleeping,Both
3,3,2006,Annual,8.63,0.024,All days,15 years and over,Sleeping,Both
4,4,2007,Annual,8.57,0.024,All days,15 years and over,Sleeping,Both
5,5,2008,Annual,8.60,0.023,All days,15 years and over,Sleeping,Both
6,6,2009,Annual,8.67,0.023,All days,15 years and over,Sleeping,Both
7,7,2010,Annual,8.67,0.024,All days,15 years and over,Sleeping,Both
8,8,2011,Annual,8.71,0.026,All days,15 years and over,Sleeping,Both
9,9,2012,Annual,8.73,0.026,All days,15 years and over,Sleeping,Both
10,10,2013,Annual,8.74,0.027,All days,15 years and over,Sleeping,Both
11,11,2014,Annual,8.80,0.025,All days,15 years and over,Sleeping,Both
12,12,2015,Annual,8.83,0.027,All days,15 years and over,Sleeping,Both
13,13,2016,Annual,8.79,0.028,All days,15 years and over,Sleeping,Both
14,14,2017,Annual,8.80,0.027,All days,15 years and over,Sleeping,Both
15,15,2003,Annual,8.26,0.023,Nonholiday weekdays,15 years and over,Sleeping,Both

Year, Avg hours per day sleeping, Activity, Sex, Period. We could use these column to track how many hours groups are sleeping on average per year, see the difference between different years, and even compare sleep hours in a year between non-holiday weekdays and all days periods.

🌟 Exercise 6: Identifying Data Types
Below are various data sources. Identify whether each one is an example of structured or unstructured data.

A company’s financial reports stored in an Excel file. Structured data.
Photographs uploaded to a social media platform. Unstructured data.
A collection of news articles on a website. Unstructured data.
Inventory data in a relational database. Structured data.
Recorded interviews from a market research study. Unstructured data.

🌟 Exercise 7: Transformation Exercise
For each of the following unstructured data sources, propose a method to convert it into structured data. Explain your reasoning.

A series of blog posts about travel experiences. Extract locations, dates, place names. Tag posts by themes. Output a table with columns such as post_id, location, date, topics. Text is unstructured, but the information it provides is worth and capable of being extracted to rows and columns.

Audio recordings of customer service calls. Turn audio into text using speech-to-text, and then use keywords (type of complaints, product names, etc...) and data about the call (duration, timestamps, id of the customer and the call agent) and output a table with call_id, duration, issue_category. Transcribing speech into text can be used similarly to the blog posts.

Handwritten notes from a brainstorming session. Use handwriting recognition to digitize the text and then categorize each note / idea into columns like id, category, idea_provider (if exists). We turned handwriting into a structured data.

A video tutorial on cooking. Transcribe speech-to-text to capture instructions and ingredients, and use computer vision to detect frame changes, timestamp them, and combine them into a table with columns like step_number, timestamp, instruction_text, ingredients.

🌟 Exercise 8 : Import a file from Kaggle
Note: This dataset was originally sourced from Kaggle, but for easier access, it has been made available on GitHub.

👉 Please download the dataset directly from the GitHub repository to use it in this project.

Import the train dataset. Use the train.csv file.
Print the first few rows of the DataFrame.

In [16]:
train = pd.read_csv('train.csv')
print(train.head())

   PassengerId  Survived  Pclass  \
0            1         0       3
1            2         1       1
2            3         1       3
3            4         1       1
4            5         0       3

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1
2                             Heikkinen, Miss. Laina  female  26.0      0
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1
4                           Allen, Mr. William Henry    male  35.0      0

   Parch            Ticket     Fare Cabin Embarked
0      0         A/5 21171   7.2500   NaN        S
1      0          PC 17599  71.2833   C85        C
2      0  STON/O2. 3101282   7.9250   NaN        S
3      0            113803  53.1000  C123        S
4      0            373450   8.0500   NaN        S

🌟 Exercise 9 : Export a dataframe to excel format and JSON format.
Create a simple dataframe.
Export the dataframe to an excel file.
Export the dataframe to a JSON file.

In [18]:
df = pd.DataFrame({
    "name": ["Ido", "Maayan", "Kiara"],
    "age": [28, 29, 1],
    "city": ["Holon", "Holon", "Holon"]
})

df.to_excel("output.xlsx", index=False)

df.to_json("output.json", orient="records", indent=4)

🌟 Exercise 10: Reading JSON Data
Use a sample JSON dataset

Import the JSON data from the provided URL.
Use Pandas to read the JSON data.
Display the first five entries of the data.

In [20]:
posts = pd.read_json("posts.json")

posts.head()

,userId,id,title,body
0,1,1,sunt aut facere repellat provident occaecati e...,quia et suscipit\nsuscipit recusandae consequu...
1,1,2,qui est esse,est rerum tempore vitae\nsequi sint nihil repr...
2,1,3,ea molestias quasi exercitationem repellat qui...,et iusto sed quo iure\nvoluptatem occaecati om...
3,1,4,eum et est occaecati,ullam et saepe reiciendis voluptatem adipisci\...
4,1,5,nesciunt quas odio,repudiandae veniam quaerat sunt sed\nalias aut...